using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using MasterServerToolkit.Networking;
using MasterServerToolkit.Utils;

namespace MasterServerToolkit.MasterServer
{
    public class Account_Info : MonoBehaviour
    {
        public ObservableServerProfile Request_New_Profile(string userId, IPeer clientPeer)
        {
            return new ObservableServerProfile(userId, clientPeer)
            {
                new ObservableString((short)MstProFilePropertyCode.DisplayName, "Name"),
                new ObservableInt((short)MstProFilePropertyCode.Player_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Player_Level, 1),
                new ObservableInt((short)MstProFilePropertyCode.Diamond, 100),
                new ObservableInt((short)MstProFilePropertyCode.Gold, 1000),
                new ObservableInt((short)MstProFilePropertyCode.Token_01, 1000),
                new ObservableInt((short)MstProFilePropertyCode.Token_02, 1000),
                new ObservableInt((short)MstProFilePropertyCode.Token_03, 1000),
                new ObservableInt((short)MstProFilePropertyCode.Token_04, 1000),
                new ObservableInt((short)MstProFilePropertyCode.Token_05, 1000),
                new ObservableInt((short)MstProFilePropertyCode.Token_06, 1000),
                new ObservableInt((short)MstProFilePropertyCode.Token_07, 1000),
                new ObservableInt((short)MstProFilePropertyCode.Token_08, 1000),
                new ObservableInt((short)MstProFilePropertyCode.Token_09, 1000),
                new ObservableInt((short)MstProFilePropertyCode.Token_10, 1000),

                new ObservableInt((short)MstProFilePropertyCode.Tower_101_Level, 1),
                new ObservableInt((short)MstProFilePropertyCode.Tower_101_EXP, 1),
                new ObservableInt((short)MstProFilePropertyCode.Tower_102_Level, 1),
                new ObservableInt((short)MstProFilePropertyCode.Tower_102_EXP, 1),
                new ObservableInt((short)MstProFilePropertyCode.Tower_103_Level, 1),
                new ObservableInt((short)MstProFilePropertyCode.Tower_103_EXP, 1),
                new ObservableInt((short)MstProFilePropertyCode.Tower_104_Level, 1),
                new ObservableInt((short)MstProFilePropertyCode.Tower_104_EXP, 1),
                new ObservableInt((short)MstProFilePropertyCode.Tower_105_Level, 1),
                new ObservableInt((short)MstProFilePropertyCode.Tower_105_EXP, 1),
                new ObservableInt((short)MstProFilePropertyCode.Tower_106_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_106_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_107_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_107_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_108_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_108_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_109_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_109_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_110_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_110_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_111_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_111_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_112_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_112_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_113_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_113_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_114_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_114_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_115_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_115_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_116_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_116_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_117_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_117_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_118_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_118_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_119_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_119_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_120_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_120_EXP, 0),

                new ObservableInt((short)MstProFilePropertyCode.Tower_201_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_201_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_202_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_202_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_203_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_203_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_204_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_204_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_205_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_205_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_206_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_206_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_207_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_207_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_208_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_208_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_209_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_209_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_210_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_210_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_211_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_211_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_212_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_212_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_213_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_213_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_214_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_214_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_215_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_215_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_216_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_216_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_217_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_217_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_218_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_218_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_219_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_219_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_220_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_220_EXP, 0),

                new ObservableInt((short)MstProFilePropertyCode.Tower_301_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_301_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_302_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_302_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_303_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_303_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_304_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_304_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_305_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_305_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_306_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_306_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_307_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_307_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_308_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_308_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_309_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_309_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_310_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_310_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_311_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_311_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_312_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_312_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_313_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_313_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_314_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_314_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_315_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_315_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_316_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_316_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_317_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_317_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_318_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_318_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_319_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_319_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_320_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_320_EXP, 0),

                new ObservableInt((short)MstProFilePropertyCode.Tower_401_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_401_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_402_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_402_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_403_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_403_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_404_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_404_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_405_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_405_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_406_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_406_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_407_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_407_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_408_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_408_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_409_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_409_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_410_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_410_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_411_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_411_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_412_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_412_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_413_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_413_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_414_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_414_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_415_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_415_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_416_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_416_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_417_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_417_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_418_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_418_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_419_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_419_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_420_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_420_EXP, 0),

                new ObservableInt((short)MstProFilePropertyCode.Tower_501_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_501_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_502_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_502_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_503_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_503_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_504_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_504_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_505_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_505_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_506_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_506_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_507_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_507_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_508_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_508_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_509_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_509_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_510_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_510_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_511_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_511_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_512_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_512_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_513_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_513_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_514_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_514_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_515_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_515_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_516_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_516_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_517_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_517_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_518_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_518_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_519_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_519_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_520_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_520_EXP, 0),

                new ObservableInt((short)MstProFilePropertyCode.Tower_601_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_601_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_602_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_602_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_603_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_603_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_604_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_604_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_605_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_605_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_606_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_606_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_607_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_607_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_608_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_608_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_609_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_609_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_610_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_610_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_611_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_611_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_612_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_612_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_613_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_613_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_614_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_614_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_615_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_615_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_616_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_616_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_617_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_617_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_618_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_618_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_619_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_619_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_620_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_620_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_621_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_621_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_622_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_622_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_623_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_623_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_624_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_624_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_625_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_625_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_626_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_626_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_627_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_627_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_628_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_628_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_629_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_629_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_630_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_630_EXP, 0),

                new ObservableInt((short)MstProFilePropertyCode.Tower_701_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_701_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_702_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_702_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_703_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_703_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_704_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_704_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_705_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_705_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_706_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_706_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_707_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_707_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_708_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_708_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_709_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_709_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_710_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_710_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_711_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_711_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_712_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_712_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_713_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_713_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_714_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_714_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_715_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_715_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_716_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_716_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_717_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_717_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_718_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_718_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_719_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_719_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_720_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_720_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_721_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_721_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_722_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_722_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_723_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_723_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_724_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_724_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_725_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_725_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_726_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_726_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_727_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_727_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_728_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_728_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_729_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_729_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_730_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_730_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_731_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_731_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_732_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_732_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_733_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_733_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_734_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_734_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_735_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_735_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_736_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_736_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_737_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_737_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_738_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_738_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_739_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_739_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_740_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_740_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_741_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_741_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_742_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_742_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_743_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_743_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_744_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_744_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_745_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_745_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_746_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_746_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_747_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_747_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_748_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_748_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_749_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_749_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_750_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Tower_750_EXP, 0),

                new ObservableInt((short)MstProFilePropertyCode.Statue_01_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_01_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_02_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_02_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_03_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_03_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_04_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_04_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_05_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_05_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_06_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_06_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_07_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_07_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_08_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_08_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_09_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_09_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_10_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_10_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_11_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_11_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_12_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_12_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_13_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_13_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_14_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_14_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_15_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_15_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_16_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_16_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_17_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_17_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_18_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_18_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_19_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_19_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_20_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_20_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_21_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_21_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_22_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_22_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_23_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_23_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_24_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_24_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_25_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_25_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_26_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_26_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_27_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_27_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_28_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_28_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_29_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_29_EXP, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_30_Level, 0),
                new ObservableInt((short)MstProFilePropertyCode.Statue_30_EXP, 0),

                new ObservableInt((short)MstProFilePropertyCode.Desk_1_01, 101),
                new ObservableInt((short)MstProFilePropertyCode.Desk_1_02, 102),
                new ObservableInt((short)MstProFilePropertyCode.Desk_1_03, 103),
                new ObservableInt((short)MstProFilePropertyCode.Desk_1_04, 104),
                new ObservableInt((short)MstProFilePropertyCode.Desk_1_05, 105),

                new ObservableInt((short)MstProFilePropertyCode.Desk_2_01, 101),
                new ObservableInt((short)MstProFilePropertyCode.Desk_2_02, 102),
                new ObservableInt((short)MstProFilePropertyCode.Desk_2_03, 103),
                new ObservableInt((short)MstProFilePropertyCode.Desk_2_04, 104),
                new ObservableInt((short)MstProFilePropertyCode.Desk_2_05, 105),

                new ObservableInt((short)MstProFilePropertyCode.Desk_3_01, 101),
                new ObservableInt((short)MstProFilePropertyCode.Desk_3_02, 102),
                new ObservableInt((short)MstProFilePropertyCode.Desk_3_03, 103),
                new ObservableInt((short)MstProFilePropertyCode.Desk_3_04, 104),
                new ObservableInt((short)MstProFilePropertyCode.Desk_3_05, 105),

                new ObservableInt((short)MstProFilePropertyCode.Desk_4_01, 101),
                new ObservableInt((short)MstProFilePropertyCode.Desk_4_02, 102),
                new ObservableInt((short)MstProFilePropertyCode.Desk_4_03, 103),
                new ObservableInt((short)MstProFilePropertyCode.Desk_4_04, 104),
                new ObservableInt((short)MstProFilePropertyCode.Desk_4_05, 105),

                new ObservableInt((short)MstProFilePropertyCode.Desk_5_01, 101),
                new ObservableInt((short)MstProFilePropertyCode.Desk_5_02, 102),
                new ObservableInt((short)MstProFilePropertyCode.Desk_5_03, 103),
                new ObservableInt((short)MstProFilePropertyCode.Desk_5_04, 104),
                new ObservableInt((short)MstProFilePropertyCode.Desk_5_05, 105),

                new ObservableInt((short)MstProFilePropertyCode.Desk_6_01, 101),
                new ObservableInt((short)MstProFilePropertyCode.Desk_6_02, 102),
                new ObservableInt((short)MstProFilePropertyCode.Desk_6_03, 103),
                new ObservableInt((short)MstProFilePropertyCode.Desk_6_04, 104),
                new ObservableInt((short)MstProFilePropertyCode.Desk_6_05, 105),

                new ObservableInt((short)MstProFilePropertyCode.Desk_7_01, 101),
                new ObservableInt((short)MstProFilePropertyCode.Desk_7_02, 102),
                new ObservableInt((short)MstProFilePropertyCode.Desk_7_03, 103),
                new ObservableInt((short)MstProFilePropertyCode.Desk_7_04, 104),
                new ObservableInt((short)MstProFilePropertyCode.Desk_7_05, 105),

                new ObservableInt((short)MstProFilePropertyCode.Desk_8_01, 101),
                new ObservableInt((short)MstProFilePropertyCode.Desk_8_02, 102),
                new ObservableInt((short)MstProFilePropertyCode.Desk_8_03, 103),
                new ObservableInt((short)MstProFilePropertyCode.Desk_8_04, 104),
                new ObservableInt((short)MstProFilePropertyCode.Desk_8_05, 105),

                new ObservableInt((short)MstProFilePropertyCode.Selected_Map, 1),
                new ObservableInt((short)MstProFilePropertyCode.Map_01, 1),
                new ObservableInt((short)MstProFilePropertyCode.Map_02, 0),
                new ObservableInt((short)MstProFilePropertyCode.Map_03, 0),
                new ObservableInt((short)MstProFilePropertyCode.Map_04, 0),
                new ObservableInt((short)MstProFilePropertyCode.Map_05, 0),
                new ObservableInt((short)MstProFilePropertyCode.Map_06, 0),
                new ObservableInt((short)MstProFilePropertyCode.Map_07, 0),
                new ObservableInt((short)MstProFilePropertyCode.Map_08, 0),
                new ObservableInt((short)MstProFilePropertyCode.Map_09, 0),
                new ObservableInt((short)MstProFilePropertyCode.Map_10, 0),
                new ObservableInt((short)MstProFilePropertyCode.Map_11, 0),
                new ObservableInt((short)MstProFilePropertyCode.Map_12, 0),
                new ObservableInt((short)MstProFilePropertyCode.Map_13, 0),
                new ObservableInt((short)MstProFilePropertyCode.Map_14, 0),
                new ObservableInt((short)MstProFilePropertyCode.Map_15, 0),

                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_101, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_102, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_103, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_104, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_105, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_106, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_107, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_108, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_109, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_110, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_111, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_112, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_113, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_114, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_115, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_116, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_117, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_118, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_119, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_120, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_121, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_122, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_123, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_124, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_125, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_126, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_127, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_128, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_129, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_130, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_131, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_132, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_133, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_134, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_135, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_136, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_137, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_138, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_139, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_140, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_141, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_142, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_143, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_144, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_145, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_146, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_147, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_148, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_149, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_150, 0),

                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_201, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_202, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_203, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_204, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_205, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_206, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_207, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_208, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_209, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_210, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_211, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_212, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_213, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_214, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_215, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_216, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_217, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_218, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_219, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_220, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_221, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_222, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_223, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_224, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_225, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_226, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_227, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_228, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_229, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_230, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_231, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_232, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_233, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_234, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_235, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_236, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_237, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_238, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_239, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_240, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_241, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_242, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_243, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_244, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_245, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_246, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_247, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_248, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_249, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_250, 0),

                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_301, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_302, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_303, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_304, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_305, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_306, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_307, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_308, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_309, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_310, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_311, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_312, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_313, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_314, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_315, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_316, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_317, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_318, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_319, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_320, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_321, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_322, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_323, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_324, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_325, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_326, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_327, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_328, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_329, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_330, 0),

                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_401, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_402, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_403, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_404, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_405, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_406, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_407, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_408, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_409, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_410, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_411, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_412, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_413, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_414, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_415, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_416, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_417, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_418, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_419, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_420, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_421, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_422, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_423, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_424, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_425, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_426, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_427, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_428, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_429, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_430, 0),

                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_501, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_502, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_503, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_504, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_505, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_506, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_507, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_508, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_509, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_510, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_511, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_512, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_513, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_514, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_515, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_516, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_517, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_518, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_519, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_520, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_521, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_522, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_523, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_524, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_525, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_526, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_527, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_528, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_529, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_530, 0),

                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_601, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_602, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_603, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_604, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_605, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_606, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_607, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_608, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_609, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_610, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_611, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_612, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_613, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_614, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_615, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_616, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_617, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_618, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_619, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_620, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_621, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_622, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_623, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_624, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_625, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_626, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_627, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_628, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_629, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_630, 0),

                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_701, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_702, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_703, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_704, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_705, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_706, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_707, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_708, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_709, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_710, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_711, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_712, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_713, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_714, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_715, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_716, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_717, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_718, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_719, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_720, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_721, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_722, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_723, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_724, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_725, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_726, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_727, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_728, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_729, 0),
                new ObservableInt((short)MstProFilePropertyCode.ClaimReward_730, 0),

                new ObservableInt((short)MstProFilePropertyCode.Selected_Icon, 1),
                new ObservableInt((short)MstProFilePropertyCode.Icon_01, 1),
                new ObservableInt((short)MstProFilePropertyCode.Icon_02, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_03, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_04, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_05, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_06, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_07, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_08, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_09, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_10, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_11, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_12, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_13, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_14, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_15, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_16, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_17, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_18, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_19, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_20, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_21, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_22, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_23, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_24, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_25, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_26, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_27, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_28, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_29, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_30, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_31, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_32, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_33, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_34, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_35, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_36, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_37, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_38, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_39, 0),
                new ObservableInt((short)MstProFilePropertyCode.Icon_40, 0),

                new ObservableInt((short)MstProFilePropertyCode.Selected_Emoji_01, 1),
                new ObservableInt((short)MstProFilePropertyCode.Selected_Emoji_02, 1),
                new ObservableInt((short)MstProFilePropertyCode.Selected_Emoji_03, 1),
                new ObservableInt((short)MstProFilePropertyCode.Selected_Emoji_04, 1),
                new ObservableInt((short)MstProFilePropertyCode.Selected_Emoji_05, 1),

                new ObservableInt((short)MstProFilePropertyCode.Emoji_01, 1),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_02, 1),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_03, 1),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_04, 1),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_05, 1),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_06, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_07, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_08, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_09, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_10, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_11, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_12, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_13, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_14, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_15, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_16, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_17, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_18, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_19, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_20, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_21, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_22, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_23, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_24, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_25, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_26, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_27, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_28, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_29, 0),
                new ObservableInt((short)MstProFilePropertyCode.Emoji_30, 0),

                new ObservableInt((short)MstProFilePropertyCode.Current_Desk, 1),
                new ObservableInt((short)MstProFilePropertyCode.Timer_01, 0),
                new ObservableInt((short)MstProFilePropertyCode.Timer_02, 0),
                new ObservableInt((short)MstProFilePropertyCode.Timer_03, 0),
                new ObservableInt((short)MstProFilePropertyCode.Timer_04, 0),
                new ObservableInt((short)MstProFilePropertyCode.Timer_05, 0),
                new ObservableInt((short)MstProFilePropertyCode.Critical_Damage, 500),

                new ObservableInt((short)MstProFilePropertyCode.D_Task_1_Type, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Task_2_Type, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Task_3_Type, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Task_1_QTY, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Task_2_QTY, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Task_3_QTY, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Task_Current_QTY_1, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Task_Current_QTY_2, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Task_Current_QTY_3, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_Task_1_Type, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_Task_2_Type, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_Task_3_Type, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_Task_1_QTY, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_Task_2_QTY, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_Task_3_QTY, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_Task_Current_QTY_1, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_Task_Current_QTY_2, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_Task_Current_QTY_3, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_1_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_1_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_Level_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_2_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_2_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_Level_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_3_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_3_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_Level_3_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_4_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_4_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_Level_4_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_5_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_5_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_Level_5_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_6_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_6_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_Level_6_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_7_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_7_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_Level_7_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_8_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_8_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_Level_8_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_9_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_9_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.D_Reward_Level_9_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_1_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_1_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_Level_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_2_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_2_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_Level_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_3_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_3_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_Level_3_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_4_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_4_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_Level_4_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_5_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_5_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_Level_5_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_6_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_6_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_Level_6_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_7_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_7_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_Level_7_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_8_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_8_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_Level_8_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_9_1_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_9_2_Claim, 0),
                new ObservableInt((short)MstProFilePropertyCode.W_RewarW_Level_9_Claim, 0),

                new ObservableInt((short)MstProFilePropertyCode.Last_Refresh_Sell_Time, 0),
                new ObservableInt((short)MstProFilePropertyCode.Last_Refresh_Exchange_Time, 0),
                new ObservableInt((short)MstProFilePropertyCode.Refresh_InGame_Sell, 0),
                new ObservableInt((short)MstProFilePropertyCode.Refresh_Exchange, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_Sell_01, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_Sell_02, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_Sell_03, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_Sell_04, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_Sell_05, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_Sell_06, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_Sell_07, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_Sell_08, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_Sell_09, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_Sell_10, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_Sell_11, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_Sell_12, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_Sell_13, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_Sell_14, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_QTY_01, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_QTY_02, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_QTY_03, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_QTY_04, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_QTY_05, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_QTY_06, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_QTY_07, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_QTY_08, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_QTY_09, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_QTY_10, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_QTY_11, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_QTY_12, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_QTY_13, 0),
                new ObservableInt((short)MstProFilePropertyCode.Special_QTY_14, 0),

                new ObservableInt((short)MstProFilePropertyCode.InGame_Sell_1, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Sell_2, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Sell_3, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Sell_4, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Sell_5, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Sell_6, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Sell_7, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Sell_8, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_QTY_1, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_QTY_2, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_QTY_3, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_QTY_4, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_QTY_5, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_QTY_6, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_QTY_7, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_QTY_8, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Price_1, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Price_2, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Price_3, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Price_4, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Price_5, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Price_6, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Price_7, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Price_8, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Currency_1, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Currency_2, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Currency_3, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Currency_4, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Currency_5, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Currency_6, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Currency_7, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Currency_8, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Sold_1, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Sold_2, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Sold_3, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Sold_4, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Sold_5, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Sold_6, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Sold_7, 0),
                new ObservableInt((short)MstProFilePropertyCode.InGame_Sold_8, 0),

                new ObservableInt((short)MstProFilePropertyCode.Exchange_1, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_2, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_3, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_4, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_5, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_6, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_7, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_8, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_QTY_1, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_QTY_2, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_QTY_3, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_QTY_4, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_QTY_5, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_QTY_6, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_QTY_7, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_QTY_8, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Price_1, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Price_2, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Price_3, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Price_4, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Price_5, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Price_6, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Price_7, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Price_8, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Currency_1, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Currency_2, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Currency_3, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Currency_4, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Currency_5, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Currency_6, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Currency_7, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Currency_8, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Sold_1, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Sold_2, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Sold_3, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Sold_4, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Sold_5, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Sold_6, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Sold_7, 0),
                new ObservableInt((short)MstProFilePropertyCode.Exchange_Sold_8, 0),

                new ObservableInt((short)MstProFilePropertyCode.Pack_Sell_1, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Sell_2, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Sell_3, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Sell_4, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Sell_5, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Sell_6, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Sell_7, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Sell_8, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_QTY_1, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_QTY_2, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_QTY_3, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_QTY_4, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_QTY_5, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_QTY_6, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_QTY_7, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_QTY_8, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Price_1, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Price_2, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Price_3, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Price_4, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Price_5, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Price_6, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Price_7, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Price_8, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Currency_1, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Currency_2, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Currency_3, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Currency_4, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Currency_5, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Currency_6, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Currency_7, 0),
                new ObservableInt((short)MstProFilePropertyCode.Pack_Currency_8, 0),
            };
        }

        public bool Compare_Server_and_Local_Profile(ObservableProfile server, ObservableProfile local)
        {
            bool All_Property_is_Same = true;
            string[] MstProFilePropertyCode_Names = System.Enum.GetNames(typeof(MstProFilePropertyCode));
            string Server_Name = null, Local_Name = null;
            int Server_Property = 0, Local_Property = 0;
            for (int i = 0; i < MstProFilePropertyCode_Names.Length; i++)
            {
                string code = MstProFilePropertyCode_Names[i];
                if (code == "DisplayName")
                {
                    Server_Name = Get_PropertyString_by_String(server, code).GetValue();
                    Local_Name = Get_PropertyString_by_String(local, code).GetValue();
                    bool same_Property = Compare_String(Server_Name, Local_Name, code);
                    if (!same_Property)
                    {
                        Debug.Log("same_Property || " + same_Property);
                        return false;
                    }
                }
                if (code != "DisplayName" && code != "Error")
                {
                    Server_Property = Get_PropertyInt_by_String(server, code).GetValue();
                    Local_Property = Get_PropertyInt_by_String(local, code).GetValue();
                    bool same_Property = Compare_Property(Server_Property, Local_Property, code);
                    if (!same_Property)
                    {
                        Debug.Log("same_Property || " + same_Property);
                        return false;
                    }
                }
            }

            return All_Property_is_Same;

            ObservableString Get_PropertyString_by_String(ObservableProfile profile, string Code)
            {
                short code = (short)(MstProFilePropertyCode)System.Enum.Parse(typeof(MstProFilePropertyCode), Code);
                var property = profile.GetProperty<ObservableString>(code);
                return property;
            }

            ObservableInt Get_PropertyInt_by_String(ObservableProfile profile, string Code)
            {
                short code = (short)(MstProFilePropertyCode)System.Enum.Parse(typeof(MstProFilePropertyCode), Code);
                var property = profile.GetProperty<ObservableInt>(code);
                return property;
            }

            bool Compare_String(string Server, string Local, string code)
            {
                if (Server != Local)
                {
                    Debug.Log("Server || " + Server + " || " + Local + " || " + code);
                    return false;
                }

                if (Server == Local)
                {
                    //Debug.Log("Server || " + Server + " || " + Local + " || " + code);
                    return true;
                }
                return false;
            }

            bool Compare_Property(int Server, int Local, string code)
            {
                if (Server != Local)
                {
                    Debug.Log("Server || " + Server + " || " + Local + " || " + code);
                    return false;
                }

                if (Server == Local)
                {
                    //Debug.Log("Server || " + Server + " || " + Local + " || " + code);
                    return true;
                }
                return false;
            }
        }
    }
}
